// <auto-generated />
using System;
using CTWebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CTWebAPI.Migrations
{
    [DbContext(typeof(CoinTreeDBContext))]
    partial class CoinTreeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("CTWebAPI.Models.CryptoRates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ask")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("bid")
                        .HasColumnType("TEXT");

                    b.Property<string>("buy")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("changepercentage")
                        .HasColumnType("TEXT");

                    b.Property<string>("market")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("rate")
                        .HasColumnType("TEXT");

                    b.Property<string>("rateSteps")
                        .HasColumnType("TEXT");

                    b.Property<string>("rateType")
                        .HasColumnType("TEXT");

                    b.Property<string>("sell")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("spotRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CryptoRates");
                });
#pragma warning restore 612, 618
        }
    }
}
